### ISSUE TITLE
Meme

### ISSUE THREAD

**Issue by Pabloutndev** [pdepjm/2024-tp0-presentacion-MNVallone#2]
Consejo formal: Seria interesante saber que tipo de videojuegos te gustan? ()

Consejo memero: Puedes añadir el tema de "no te olvides el where en el delete from" https://www.youtube.com/watch?v=i_cVJgIz_Cs 😂

**Comment by MNVallone** [comment]
Gracias por la sugerencia, ya realice los cambios pertinentes 😎.
